baseURL = "https://gianlucacini.com"
title = "Gianluca Cini"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
ignoreErrors = ["error-missing-instagram-accesstoken"]

[params]
  description = ""
  dark = "on"
  highlight = true

[menu]
  #[[menu.main]]
  #  identifier = "posts"
  #  name = "posts"
  #  title = "posts"
  #  url = "/"
  #  weight = 10

   [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags"
    weight = 10

    [[menu.main]]
    identifier = "github"
    name = "github"
    title = "Github"
    url = "https://github.com/gianlucacini"
    weight = 20

    [[menu.main]]
    identifier = "linkedin"
    name = "linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/gianluca-cini/"
    weight = 30

[[menu.main]]
    identifier = "instagram"
    name = "instagram"
    title = "Instagram"
    url = "https://www.instagram.com/gianluca_cini/"
    weight = 40



[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
